title: Programacion
logo: /assets/img/logo.png
logo_linda_3: /assets/images/spg.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
cliente: Linda
